from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
from typing import List, Dict

class DocumentEngine:
    def __init__(self):
        pass

    def generate_docx(self, assessment_data: dict) -> io.BytesIO:
        """
        Generates a DOCX report from assessment data.
        """
        document = Document()
        
        # Title
        title = document.add_heading('Safety Assessment Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Risk Summary
        document.add_heading('Risk Summary', level=1)
        p = document.add_paragraph()
        p.add_run('Risk Level: ').bold = True
        risk_run = p.add_run(assessment_data['risk_level'])
        if assessment_data['risk_level'] == 'High':
            risk_run.font.color.rgb = None # default logic, can't easily set RGB without imports
            risk_run.bold = True
        
        p.add_run(f"\nRisk Score: {assessment_data['risk_score']}")
        p.add_run(f"\nConfidence: {assessment_data['confidence']}")

        # Hazards
        document.add_heading('Identified Hazards', level=1)
        if assessment_data['hazards']:
            for h in assessment_data['hazards']:
                document.add_paragraph(h, style='List Bullet')
        else:
            document.add_paragraph("No specific hazards identified.")

        # Controls
        document.add_heading('Required Controls', level=1)
        if assessment_data['controls']:
            table = document.add_table(rows=1, cols=2)
            table.style = 'Table Grid'
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Type'
            hdr_cells[1].text = 'Control Measure'
            
            for c in assessment_data['controls']:
                row_cells = table.add_row().cells
                row_cells[0].text = c['type']
                row_cells[1].text = c['description']
        else:
            document.add_paragraph("No controls specified.")

        # HIRA Table Stub
        document.add_heading('HIRA Details', level=1)
        document.add_paragraph('This report was automatically generated by SafetyAI Guardian.')

        # Save to memory
        file_stream = io.BytesIO()
        document.save(file_stream)
        file_stream.seek(0)
        return file_stream

    def generate_pdf(self, assessment_data: dict) -> io.BytesIO:
        """
        Generates a PDF report using ReportLab.
        """
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(Paragraph("Safety Assessment Report", styles['Title']))
        story.append(Spacer(1, 12))

        # Risk Summary
        story.append(Paragraph("Risk Summary", styles['Heading1']))
        risk_text = f"<b>Risk Level:</b> {assessment_data['risk_level']}<br/>" \
                    f"<b>Risk Score:</b> {assessment_data['risk_score']}<br/>" \
                    f"<b>Confidence:</b> {assessment_data['confidence']}"
        story.append(Paragraph(risk_text, styles['Normal']))
        story.append(Spacer(1, 12))

        # Hazards
        story.append(Paragraph("Identified Hazards", styles['Heading1']))
        if assessment_data['hazards']:
            for h in assessment_data['hazards']:
                story.append(Paragraph(f"• {h}", styles['Normal']))
        else:
            story.append(Paragraph("No specific hazards identified.", styles['Normal']))
        story.append(Spacer(1, 12))

        # Controls
        story.append(Paragraph("Required Controls", styles['Heading1']))
        if assessment_data['controls']:
            table_data = [['Type', 'Control Measure']]
            for c in assessment_data['controls']:
                table_data.append([c['type'], c['description']])
            
            t = Table(table_data, colWidths=[100, 350])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('WORDWRAP', (0, 0), (-1, -1), True) # Ensure text wraps
            ]))
            story.append(t)
        else:
            story.append(Paragraph("No controls specified.", styles['Normal']))
        
        story.append(Spacer(1, 24))
        story.append(Paragraph("This report was automatically generated by SafetyAI Guardian.", styles['Italic']))

        doc.build(story)
        buffer.seek(0)
        return buffer
